#!/bin/bash

# Find the PID of the 7-highlander process
PID=$(pgrep -f "7-highlander")

if [ -n "$PID" ]; then
    # Send SIGTERM signal to the process
    kill "$PID"
else
    echo "7-highlander process not found"
fi
