#!/usr/bin/env bash
# Script that kills the 7-highlander process using SIGKILL signal

# Find the PID of the 7-highlander process
pgrep -f "7-highlander" | while read -r pid; do
    kill -9 "$pid"
done
