#!/usr/bin/env bash
# This script displays the content of the current directory in list format, showing only the part after the first dash

for file in *
do
    if [[ -e "$file" && "$file" != .* ]]
    then
        echo "${file#*-}"
    fi
done
